# Generated by Django 5.2.2 on 2025-06-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
